language: cpp
branches:
    only:
        - master
matrix:
    include:
        - os: linux
          dist: trusty
        - os: osx
          osx_image: xcode8.3
cache:
    ccache: true
    directories:
        - $HOME/.hunter
script:
    - cmake -DETHASHCUDA=Off -DETHSTRATUM=On -DETHASHCL=On -H. -Bbuild
    - cmake --build build
    - build/ethminer/ethminer --list-devices -G