version: "{build}"
branches:
  only:
    - master
os: Visual Studio 2015
configuration:
  - Release
cache:
  - C:/.hunter/_Base/Cache
install:
before_build:
  - cmake -G "Visual Studio 14 2015 Win64" -H. -Bbuild
build_script:
  - cmake --build build --config Release
after_build:
  - cmake --build build --config Release --target package
artifacts:
  - path: build/ethminer-*.zip
