version: "{build}"
branches:
  only:
    - master
    - /v\d+\..+/
os: Visual Studio 2015
configuration:
  - Release
cache:
  - C:/.hunter/_Base/Cache
install:
before_build:
  - cmake -G "Visual Studio 14 2015 Win64" -H. -Bbuild
build_script:
  - cmake --build build --config Release
after_build:
  - cmake --build build --config Release --target package

artifacts:
  - path: build/ethminer-*.zip
    name: ethminer

before_deploy:
  - . build/variables.ps
  - echo ethminer $ethminer_version (prerelease $ethminer_version_is_prerelease)
deploy:
  release: ethminer $ethminer_version
  description: ''
  provider: GitHub
  auth_token:
    secure: uDRcvbW+9GIyKlZ9guJfWOQ6jg0An6eULg6mEkYgdKn/GVNpYSKvO5oHxP0U8a+e
  artifact: ethminer
  draft: true
  prerelease: $ethminer_version_is_prerelease
  force_update: false
  on:
    appveyor_repo_tag: true
