version: "{build}"
branches:
  only:
    - master
    - /v\d+\..+/
os: Visual Studio 2015
configuration:
  - Release
cache:
  - C:/.hunter/_Base/Cache
install:
before_build:
  - cmake -G "Visual Studio 14 2015 Win64" -H. -Bbuild
build_script:
  - cmake --build build --config Release
after_build:
  - cmake --build build --config Release --target package

artifacts:
  - path: build/ethminer-*.zip
    name: ethminer
deploy:
  tag: $(appveyor_repo_tag_name)
  description: ''
  provider: GitHub
  auth_token:
    secure: uDRcvbW+9GIyKlZ9guJfWOQ6jg0An6eULg6mEkYgdKn/GVNpYSKvO5oHxP0U8a+e
  artifact: ethminer
  draft: false
  prerelease: true
  force_update: true
  on:
    appveyor_repo_tag: true
