version: 2
jobs:
  build:
    docker:
<<<<<<< HEAD
      - image: nvidia/cuda:9.0-devel-ubuntu17.04
=======
      - image: nvidia/cuda:9.1-devel-ubuntu16.04
>>>>>>> d7d14d64648833064eef1cd52de7dec65641c1c7
    steps:
      - checkout

      - run: apt-get update && apt-get install -qy cmake mesa-common-dev libidn11-dev
      - restore_cache:
          key: hunter-v3
      - run: cmake -DHUNTER_JOBS_NUMBER=4 -DETHASHCUDA=ON -DAPICORE=ON -H. -Bbuild
      - save_cache:
          key: hunter-v3
          paths:
            - /root/.hunter/_Base/Cache
      - run: cmake --build build -- -j4
      - store_artifacts:
          path: build/ethminer/ethminer
          destination: ethminer
